apiVersion: 1.0.0                                
previews:

- name: default
  container:
    image: us-east1-docker.pkg.dev/core-workshop/workshop-registry/microblog-frontend:${{env.commit.shortSha}}
    ports:
    - value: 80
